library_paths:
    shotgun: '<path to shotgun package>'

shotgun:
    connection:
        site: '<shotgun site url>'
        script_name: '<script name>'
        api_key: '<api key>'
    sample_generation:
        word_site: "http://svnweb.freebsd.org/csrg/share/dict/words?view=co&content-type=text/plain"
        sample_word_count: 300
    data:
        target_schema: 'Task'
        keyword:
            feature_list: []
        value:
            feature_list: []
        text:
            feature_list: ['sg_description', 'tags', 'content']
        cost: 'time_logs_sum'

machine_learning:

statistics:
