library_paths:
    shotgun: 'z:\Dev\python-api'

shotgun:
    connection:
        site: 'https://temporary.shotgunstudio.com'
        script_name: 'test'
        api_key: '7dec6edd4fc0b8de83ffc2c890b089288801b4e923454233148f5b053d153bd8'
    sample_generation:
        word_site: "http://svnweb.freebsd.org/csrg/share/dict/words?view=co&content-type=text/plain"
        sample_word_count: 300
    data:
        target_schema: 'Task'
        keyword:
            feature_list: []
        value:
            feature_list: []
        text:
            feature_list: ['sg_description', 'tags', 'content']
        cost: 'time_logs_sum'

machine_learning:

statistics:
