library_paths:
    shotgun: 'Z:\Dev\python-api'

model:
trainer:
data_processor:
analyze_report_export_directory: './analyze_report'
resource_handler:
source_generator:
    shotgun:
        connection:
            site: 'https://mathleonb.shotgunstudio.com'
            script_name: 'api_test'
            api_key: '66d137c6642dcf730bddc7bd3ca06f717b4ab703186cef238f643c02c890f9c7'
        data:
            source_schema: 'Shot' # Target Granularity
            text:
                feature_list: ['description', 'tags', 'notes', 'open_notes']
            cost: 'duration'
            skip_features: ['id', 'created_at', 'image', 'project', 'updated_at']
