skip_feature_for_df_x_full:
- cut_duration
- cut_in
- cut_out
- filmstrip_image
- head_duration
- head_in
- head_out
- sg_shot_type
- smart_cut_duration
- smart_cut_in
- smart_cut_out
- smart_cut_summary_display
- smart_duration_summary_display
- smart_head_duration
- smart_head_in
- smart_head_out
- smart_tail_duration
- smart_tail_in
- smart_tail_out
- smart_working_duration
- step_0
- step_106
- step_2
- step_35
- step_6
- step_7
- step_8
- tail_duration
- tail_in
- tail_out
- task_template
- updated_by
- assets__alice
- assets__anders
- assets__banning
- assets__branch
- assets__bus
- assets__car
- assets__caterpillar
- assets__darcy
- assets__deserted
- assets__fern
- assets__flash
- assets__flower
- assets__forest
- assets__island
- assets__launcher
- assets__leaf
- assets__morning
- assets__mouse
- assets__mrs
- assets__night
- assets__pickup
- assets__police
- assets__scary
- assets__school
- assets__spoon
- assets__squirrel
- assets__stormy
- assets__street
- assets__submarine
- assets__sunny
- assets__tank
- assets__top
- assets__tractor
- assets__trolley
- assets__tunnel
- sg_cut_duration
- sg_cut_in
- sg_cut_order
- sg_cut_out
- sg_tail_out
- sg_working_duration
skip_feature_for_df_x_text_full:
- _i_
- above
- across
- ada
- added
- adding
- adoption
- advice
- afraid
- against
- age
- ahem
- air
- airs
- alarm
- alices
- allow
- almost
- alone
- along
- altoget
- altogether
- always
- among
- angrily
- angry
- annoyed
- answer
- anxiously
- anything
- appeared
- apple
- arm
- arms
- arranged
- ashamed
- asking
- attending
- avoid
- away
- bad
- bank
- bark
- bathing
- bats
- beasts
- beautifully
- because
- bed
- bee
- been
- before
- begun
- behind
- being
- believe
- bend
- besides
- best
- better
- bill
- bills
- birds
- bit
- blow
- bones
- book
- books
- bottle
- box
- brain
- branches
- bright
- brightened
- bring
- bringing
- broken
- burn
- busy
- buttercup
- butterfly
- by
- cake
- cakes
- called
- came
- can
- candle
- cant
- capital
- care
- carefully
- case
- catch
- catching
- caterpillar
- cats
- certain
- certainly
- change
- changed
- changes
- changing
- charges
- cheated
- child
- children
- chimney
- chin
- choked
- chorus
- chose
- circle
- close
- coaxing
- come
- comes
- comfort
- coming
- commotion
- concluded
- consultation
- contempt
- contradicted
- conversation
- corner
- could
- course
- crab
- cried
- croquet
- crossly
- crouched
- crowded
- cry
- crying
- cucumber
- cupboards
- curious
- curled
- currants
- curtain
- day
- deal
- dear
- dears
- decided
- decidedly
- declare
- deep
- deepest
- delight
- delighted
- denying
- despair
- desperate
- did
- different
- difficult
- difficulty
- dinah
- dinahll
- dinahs
- dipped
- directly
- dodo
- dogs
- door
- doors
- doth
- doubt
- doubtfully
- draw
- drew
- drop
- dropped
- drunk
- dry
- duck
- dull
- each
- easily
- eats
- edge
- effe
- effect
- eggs
- either
- else
- empty
- english
- engraved
- enough
- entangled
- escape
- every
- everything
- exact
- excellent
- executed
- explain
- eyed
- eyes
- face
- fallen
- falling
- familiarly
- family
- fan
- fancy
- fanning
- far
- fat
- fear
- feel
- feelings
- feet
- fell
- fellow
- felt
- fender
- ferrets
- few
- field
- fifteen
- fifth
- filled
- find
- fire
- first
- fitted
- fixed
- flashed
- flustered
- fond
- foot
- forgot
- forgotten
- four
- frame
- free
- frightened
- frog
- from
- frowning
- full
- fur
- game
- general
- generally
- getting
- girl
- girls
- give
- glass
- gloves
- goes
- going
- golden
- gone
- good
- goose
- grand
- gravely
- grow
- grown
- guessed
- hadn
- hand
- handed
- hands
- happen
- happened
- happens
- hard
- hardly
- has
- hastily
- hatching
- hated
- haven
- having
- head
- heads
- hear
- heard
- hearing
- hedge
- heels
- height
- held
- help
- hide
- hiss
- hit
- hold
- hole
- home
- honour
- hope
- hot
- house
- houses
- however
- humbly
- hung
- hurried
- hurt
- idea
- immediate
- important
- inches
- indeed
- injure
- instantly
- invent
- itself
- jack
- jar
- jumped
- keep
- kept
- key
- kick
- kid
- killing
- kneel
- knowing
- known
- label
- ladder
- lap
- large
- larger
- last
- late
- latitude
- lazily
- leaders
- leant
- learn
- least
- left
- legged
- legs
- lesson
- lessons
- let
- letters
- licking
- life
- likely
- listen
- listening
- lizard
- lodging
- longer
- longitude
- looked
- looking
- lory
- love
- lovely
- low
- lying
- machines
- made
- magic
- magpie
- make
- makes
- making
- manage
- managed
- many
- maps
- marked
- mary
- matters
- may
- mean
- meaning
- melancholy
- mentioned
- messages
- mice
- middle
- might
- miles
- mind
- minutes
- miss
- moment
- morning
- most
- mouses
- mouth
- much
- mushroom
- must
- myself
- name
- narrow
- nasty
- natural
- nay
- near
- nearly
- neat
- neatly
- neck
- nervous
- nest
- never
- neverthel
- new
- next
- nibbled
- nibbling
- nice
- night
- nine
- nobody
- none
- nor
- nothing
- notice
- nowhere
- number
- 'off'
- offended
- often
- oh
- older
- once
- only
- open
- opened
- opportunity
- outside
- over
- pair
- pale
- panting
- pardon
- particular
- pat
- patiently
- pattering
- paws
- pegs
- people
- perfectly
- perhaps
- pet
- pictures
- pieces
- pigeon
- pine
- piteous
- planning
- play
- playing
- pleaded
- please
- plenty
- pocket
- pointing
- poison
- poker
- poky
- pool
- pope
- possibly
- present
- pretexts
- prizes
- promising
- puffed
- pulled
- puppy
- put
- queer
- quick
- rabbit
- rabbits
- race
- railway
- raising
- rate
- rather
- rats
- reach
- ready
- rearing
- remarkable
- remembe
- remember
- remembered
- repeat
- repeated
- replied
- resource
- rest
- result
- righthand
- ring
- rising
- roast
- rocket
- rome
- roots
- rules
- run
- running
- rush
- rushed
- sadly
- salt
- same
- sand
- say
- saying
- second
- seem
- seemed
- seems
- seen
- sending
- sensation
- series
- serpent
- serpents
- set
- severely
- shaking
- shall
- shant
- sharp
- shell
- shelves
- shes
- shi
- shore
- short
- should
- shouldnt
- show
- shriek
- shrinking
- shut
- shutting
- shy
- side
- sighing
- silence
- silent
- simply
- since
- sir
- sister
- sitting
- six
- sky
- slipped
- slowly
- small
- smaller
- smile
- smoking
- snappishly
- snatch
- soft
- solemnly
- somebody
- something
- somewhere
- soon
- sorrowful
- sorry
- sorts
- sounded
- spades
- speak
- speaking
- speech
- splash
- splashing
- spoke
- spread
- stairs
- stalk
- started
- station
- stay
- steady
- stick
- still
- stopped
- stopping
- story
- straight
- struck
- stuff
- stupid
- subject
- submitted
- succeeded
- such
- sudden
- suddenly
- suit
- suppose
- sure
- surprised
- swam
- swim
- swimming
- table
- tail
- take
- talk
- talkin
- talking
- teaching
- tears
- tell
- temper
- ten
- terrier
- than
- thank
- thatll
- thats
- these
- theyd
- thick
- thimble
- thirteen
- thistle
- those
- thought
- thoughtfully
- thousand
- three
- through
- tidy
- tie
- till
- times
- tiny
- tired
- together
- too
- took
- toys
- trees
- trembling
- tricks
- tried
- trotting
- trouble
- 'true'
- try
- trying
- tumbled
- turkey
- turned
- twelve
- two
- uncomfortable
- uncommonly
- under
- underneath
- unfolded
- unpleasant
- until
- upon
- upright
- used
- various
- venture
- violent
- violently
- voice
- voices
- vulgar
- waistcoat
- waited
- waiting
- walk
- wandered
- wandering
- want
- wanted
- washing
- wasn
- water
- well
- went
- were
- whats
- when
- whenever
- where
- whether
- whic
- which
- whiskers
- whispers
- white
- who
- whos
- why
- wild
- will
- window
- wish
- without
- wonder
- wondered
- wont
- wood
- wooden
- words
- worm
- worry
- worse
- worth
- would
- wrapping
- wretched
- write
- written
- wrong
- yawned
- yelp
- yer
- 'yes'
- yesterday
- yet
- yours
- yourself
- youth
